"""
Export a small but realistic subset of the extracted DB as a SQL file the
Worker's local D1 can load. Useful for smoke-testing the Worker against
*real* data without round-tripping the full 100K+ row DB.

Picks: top-N images by save_count, plus all their savers + saves.

Usage:
    python -m parser.export_seed out/test.db web/seed/seed-real.sql --top 200
"""

from __future__ import annotations
import argparse, sqlite3, sys
from pathlib import Path


def sql_escape(value):
    if value is None:                    return "NULL"
    if isinstance(value, (int, float)):  return str(value)
    s = str(value).replace("'", "''")
    return f"'{s}'"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("db", type=Path)
    ap.add_argument("out", type=Path)
    ap.add_argument("--top", type=int, default=200, help="number of images to export")
    args = ap.parse_args()

    if not args.db.exists():
        print(f"no such db: {args.db}", file=sys.stderr); return 1

    db = sqlite3.connect(args.db)
    db.row_factory = sqlite3.Row

    images = db.execute(
        """SELECT image_id, uploader, source_url, source_dead, cdn_thumbnail_url,
                  r2_key, width, height, uploaded_at, comment_count, save_count
           FROM images
           WHERE r2_key IS NOT NULL
           ORDER BY save_count DESC, uploaded_at DESC
           LIMIT ?""",
        (args.top,),
    ).fetchall()

    if not images:
        print("WARNING: no images with r2_key set — did you run stitch.py?", file=sys.stderr)
        # Fall back: pick by save_count regardless of bytes.
        images = db.execute(
            "SELECT * FROM images ORDER BY save_count DESC, uploaded_at DESC LIMIT ?",
            (args.top,),
        ).fetchall()

    image_ids = [r["image_id"] for r in images]
    placeholders = ",".join("?" * len(image_ids))

    saves = db.execute(
        f"SELECT image_id, username, saved_at FROM saves WHERE image_id IN ({placeholders})",
        image_ids,
    ).fetchall()

    user_set = {r["uploader"] for r in images} | {r["username"] for r in saves}
    user_set.discard(None)
    user_set.discard("_unknown")
    users = db.execute(
        f"SELECT username, display_name, joined_at, bio, save_count FROM users WHERE username IN ({','.join('?' * len(user_set))})",
        list(user_set),
    ).fetchall() if user_set else []

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as f:
        f.write("-- Auto-generated by parser.export_seed. Re-run safely: clears and reseeds.\n")
        f.write("DELETE FROM image_tags; DELETE FROM saves; DELETE FROM images_fts;\n")
        f.write("DELETE FROM images; DELETE FROM tags; DELETE FROM users;\n\n")

        # Need a "_unknown" placeholder user for any images whose uploader fell back.
        if any(r["uploader"] == "_unknown" for r in images):
            f.write("INSERT OR IGNORE INTO users (username) VALUES ('_unknown');\n")

        for u in users:
            f.write(
                "INSERT OR IGNORE INTO users (username, display_name, joined_at, bio, save_count) VALUES "
                f"({sql_escape(u['username'])}, {sql_escape(u['display_name'])}, "
                f"{sql_escape(u['joined_at'])}, {sql_escape(u['bio'])}, {sql_escape(u['save_count'])});\n"
            )

        f.write("\n")
        for r in images:
            f.write(
                "INSERT INTO images (image_id, uploader, source_url, source_dead, cdn_thumbnail_url, r2_key, width, height, uploaded_at, comment_count, save_count) VALUES "
                f"({sql_escape(r['image_id'])}, {sql_escape(r['uploader'])}, {sql_escape(r['source_url'])}, "
                f"{sql_escape(r['source_dead'])}, {sql_escape(r['cdn_thumbnail_url'])}, {sql_escape(r['r2_key'])}, "
                f"{sql_escape(r['width'])}, {sql_escape(r['height'])}, {sql_escape(r['uploaded_at'])}, "
                f"{sql_escape(r['comment_count'])}, {sql_escape(r['save_count'])});\n"
            )

        f.write("\n")
        for r in saves:
            f.write(
                "INSERT OR IGNORE INTO saves (image_id, username, saved_at) VALUES "
                f"({sql_escape(r['image_id'])}, {sql_escape(r['username'])}, {sql_escape(r['saved_at'])});\n"
            )

        f.write(
            "\nINSERT INTO images_fts (image_id, uploader, tags_text) "
            "SELECT image_id, uploader, '' FROM images;\n"
        )

    print(f"wrote {args.out}: {len(users)} users, {len(images)} images, {len(saves)} saves")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
